# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: soseedy.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "soseedy.CreateTeacherRequest" do
  end
  add_message "soseedy.Teacher" do
    optional :id, :int32, 1
    optional :username, :string, 2
    optional :password, :string, 3
    optional :domain, :string, 4
    optional :token, :string, 5
    optional :name, :string, 6
    optional :short_name, :string, 7
    optional :avatar_url, :string, 8
  end
end

module Soseedy
  CreateTeacherRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("soseedy.CreateTeacherRequest").msgclass
  Teacher = Google::Protobuf::DescriptorPool.generated_pool.lookup("soseedy.Teacher").msgclass
end
