// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: soseedy.proto

package com.instructure.soseedy;

public interface CreateTeacherRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:soseedy.CreateTeacherRequest)
    com.google.protobuf.MessageLiteOrBuilder {
}
