// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: soseedy.proto

package com.instructure.soseedy;

/**
 * Protobuf type {@code soseedy.Teacher}
 */
public  final class Teacher extends
    com.google.protobuf.GeneratedMessageLite<
        Teacher, Teacher.Builder> implements
    // @@protoc_insertion_point(message_implements:soseedy.Teacher)
    TeacherOrBuilder {
  private Teacher() {
    username_ = "";
    password_ = "";
    domain_ = "";
    token_ = "";
    name_ = "";
    shortName_ = "";
    avatarUrl_ = "";
  }
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>optional int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }
  /**
   * <code>optional int32 id = 1;</code>
   */
  private void setId(int value) {
    
    id_ = value;
  }
  /**
   * <code>optional int32 id = 1;</code>
   */
  private void clearId() {
    
    id_ = 0;
  }

  public static final int USERNAME_FIELD_NUMBER = 2;
  private java.lang.String username_;
  /**
   * <code>optional string username = 2;</code>
   */
  public java.lang.String getUsername() {
    return username_;
  }
  /**
   * <code>optional string username = 2;</code>
   */
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(username_);
  }
  /**
   * <code>optional string username = 2;</code>
   */
  private void setUsername(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    username_ = value;
  }
  /**
   * <code>optional string username = 2;</code>
   */
  private void clearUsername() {
    
    username_ = getDefaultInstance().getUsername();
  }
  /**
   * <code>optional string username = 2;</code>
   */
  private void setUsernameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    username_ = value.toStringUtf8();
  }

  public static final int PASSWORD_FIELD_NUMBER = 3;
  private java.lang.String password_;
  /**
   * <code>optional string password = 3;</code>
   */
  public java.lang.String getPassword() {
    return password_;
  }
  /**
   * <code>optional string password = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(password_);
  }
  /**
   * <code>optional string password = 3;</code>
   */
  private void setPassword(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    password_ = value;
  }
  /**
   * <code>optional string password = 3;</code>
   */
  private void clearPassword() {
    
    password_ = getDefaultInstance().getPassword();
  }
  /**
   * <code>optional string password = 3;</code>
   */
  private void setPasswordBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    password_ = value.toStringUtf8();
  }

  public static final int DOMAIN_FIELD_NUMBER = 4;
  private java.lang.String domain_;
  /**
   * <code>optional string domain = 4;</code>
   */
  public java.lang.String getDomain() {
    return domain_;
  }
  /**
   * <code>optional string domain = 4;</code>
   */
  public com.google.protobuf.ByteString
      getDomainBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(domain_);
  }
  /**
   * <code>optional string domain = 4;</code>
   */
  private void setDomain(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    domain_ = value;
  }
  /**
   * <code>optional string domain = 4;</code>
   */
  private void clearDomain() {
    
    domain_ = getDefaultInstance().getDomain();
  }
  /**
   * <code>optional string domain = 4;</code>
   */
  private void setDomainBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    domain_ = value.toStringUtf8();
  }

  public static final int TOKEN_FIELD_NUMBER = 5;
  private java.lang.String token_;
  /**
   * <code>optional string token = 5;</code>
   */
  public java.lang.String getToken() {
    return token_;
  }
  /**
   * <code>optional string token = 5;</code>
   */
  public com.google.protobuf.ByteString
      getTokenBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(token_);
  }
  /**
   * <code>optional string token = 5;</code>
   */
  private void setToken(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    token_ = value;
  }
  /**
   * <code>optional string token = 5;</code>
   */
  private void clearToken() {
    
    token_ = getDefaultInstance().getToken();
  }
  /**
   * <code>optional string token = 5;</code>
   */
  private void setTokenBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    token_ = value.toStringUtf8();
  }

  public static final int NAME_FIELD_NUMBER = 6;
  private java.lang.String name_;
  /**
   * <code>optional string name = 6;</code>
   */
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>optional string name = 6;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>optional string name = 6;</code>
   */
  private void setName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    name_ = value;
  }
  /**
   * <code>optional string name = 6;</code>
   */
  private void clearName() {
    
    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>optional string name = 6;</code>
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    name_ = value.toStringUtf8();
  }

  public static final int SHORT_NAME_FIELD_NUMBER = 7;
  private java.lang.String shortName_;
  /**
   * <code>optional string short_name = 7;</code>
   */
  public java.lang.String getShortName() {
    return shortName_;
  }
  /**
   * <code>optional string short_name = 7;</code>
   */
  public com.google.protobuf.ByteString
      getShortNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(shortName_);
  }
  /**
   * <code>optional string short_name = 7;</code>
   */
  private void setShortName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    shortName_ = value;
  }
  /**
   * <code>optional string short_name = 7;</code>
   */
  private void clearShortName() {
    
    shortName_ = getDefaultInstance().getShortName();
  }
  /**
   * <code>optional string short_name = 7;</code>
   */
  private void setShortNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    shortName_ = value.toStringUtf8();
  }

  public static final int AVATAR_URL_FIELD_NUMBER = 8;
  private java.lang.String avatarUrl_;
  /**
   * <code>optional string avatar_url = 8;</code>
   */
  public java.lang.String getAvatarUrl() {
    return avatarUrl_;
  }
  /**
   * <code>optional string avatar_url = 8;</code>
   */
  public com.google.protobuf.ByteString
      getAvatarUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(avatarUrl_);
  }
  /**
   * <code>optional string avatar_url = 8;</code>
   */
  private void setAvatarUrl(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    avatarUrl_ = value;
  }
  /**
   * <code>optional string avatar_url = 8;</code>
   */
  private void clearAvatarUrl() {
    
    avatarUrl_ = getDefaultInstance().getAvatarUrl();
  }
  /**
   * <code>optional string avatar_url = 8;</code>
   */
  private void setAvatarUrlBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    avatarUrl_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!username_.isEmpty()) {
      output.writeString(2, getUsername());
    }
    if (!password_.isEmpty()) {
      output.writeString(3, getPassword());
    }
    if (!domain_.isEmpty()) {
      output.writeString(4, getDomain());
    }
    if (!token_.isEmpty()) {
      output.writeString(5, getToken());
    }
    if (!name_.isEmpty()) {
      output.writeString(6, getName());
    }
    if (!shortName_.isEmpty()) {
      output.writeString(7, getShortName());
    }
    if (!avatarUrl_.isEmpty()) {
      output.writeString(8, getAvatarUrl());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!username_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getUsername());
    }
    if (!password_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(3, getPassword());
    }
    if (!domain_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(4, getDomain());
    }
    if (!token_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(5, getToken());
    }
    if (!name_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(6, getName());
    }
    if (!shortName_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(7, getShortName());
    }
    if (!avatarUrl_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(8, getAvatarUrl());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.instructure.soseedy.Teacher parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.instructure.soseedy.Teacher parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.instructure.soseedy.Teacher parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.instructure.soseedy.Teacher parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.instructure.soseedy.Teacher parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.instructure.soseedy.Teacher parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.instructure.soseedy.Teacher parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.instructure.soseedy.Teacher parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.instructure.soseedy.Teacher parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.instructure.soseedy.Teacher parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.instructure.soseedy.Teacher prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code soseedy.Teacher}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.instructure.soseedy.Teacher, Builder> implements
      // @@protoc_insertion_point(builder_implements:soseedy.Teacher)
      com.instructure.soseedy.TeacherOrBuilder {
    // Construct using com.instructure.soseedy.Teacher.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return instance.getId();
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public Builder setId(int value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }

    /**
     * <code>optional string username = 2;</code>
     */
    public java.lang.String getUsername() {
      return instance.getUsername();
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      return instance.getUsernameBytes();
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public Builder setUsername(
        java.lang.String value) {
      copyOnWrite();
      instance.setUsername(value);
      return this;
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public Builder clearUsername() {
      copyOnWrite();
      instance.clearUsername();
      return this;
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUsernameBytes(value);
      return this;
    }

    /**
     * <code>optional string password = 3;</code>
     */
    public java.lang.String getPassword() {
      return instance.getPassword();
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      return instance.getPasswordBytes();
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public Builder setPassword(
        java.lang.String value) {
      copyOnWrite();
      instance.setPassword(value);
      return this;
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public Builder clearPassword() {
      copyOnWrite();
      instance.clearPassword();
      return this;
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPasswordBytes(value);
      return this;
    }

    /**
     * <code>optional string domain = 4;</code>
     */
    public java.lang.String getDomain() {
      return instance.getDomain();
    }
    /**
     * <code>optional string domain = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDomainBytes() {
      return instance.getDomainBytes();
    }
    /**
     * <code>optional string domain = 4;</code>
     */
    public Builder setDomain(
        java.lang.String value) {
      copyOnWrite();
      instance.setDomain(value);
      return this;
    }
    /**
     * <code>optional string domain = 4;</code>
     */
    public Builder clearDomain() {
      copyOnWrite();
      instance.clearDomain();
      return this;
    }
    /**
     * <code>optional string domain = 4;</code>
     */
    public Builder setDomainBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDomainBytes(value);
      return this;
    }

    /**
     * <code>optional string token = 5;</code>
     */
    public java.lang.String getToken() {
      return instance.getToken();
    }
    /**
     * <code>optional string token = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      return instance.getTokenBytes();
    }
    /**
     * <code>optional string token = 5;</code>
     */
    public Builder setToken(
        java.lang.String value) {
      copyOnWrite();
      instance.setToken(value);
      return this;
    }
    /**
     * <code>optional string token = 5;</code>
     */
    public Builder clearToken() {
      copyOnWrite();
      instance.clearToken();
      return this;
    }
    /**
     * <code>optional string token = 5;</code>
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTokenBytes(value);
      return this;
    }

    /**
     * <code>optional string name = 6;</code>
     */
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>optional string name = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>optional string name = 6;</code>
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>optional string name = 6;</code>
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>optional string name = 6;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>optional string short_name = 7;</code>
     */
    public java.lang.String getShortName() {
      return instance.getShortName();
    }
    /**
     * <code>optional string short_name = 7;</code>
     */
    public com.google.protobuf.ByteString
        getShortNameBytes() {
      return instance.getShortNameBytes();
    }
    /**
     * <code>optional string short_name = 7;</code>
     */
    public Builder setShortName(
        java.lang.String value) {
      copyOnWrite();
      instance.setShortName(value);
      return this;
    }
    /**
     * <code>optional string short_name = 7;</code>
     */
    public Builder clearShortName() {
      copyOnWrite();
      instance.clearShortName();
      return this;
    }
    /**
     * <code>optional string short_name = 7;</code>
     */
    public Builder setShortNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setShortNameBytes(value);
      return this;
    }

    /**
     * <code>optional string avatar_url = 8;</code>
     */
    public java.lang.String getAvatarUrl() {
      return instance.getAvatarUrl();
    }
    /**
     * <code>optional string avatar_url = 8;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarUrlBytes() {
      return instance.getAvatarUrlBytes();
    }
    /**
     * <code>optional string avatar_url = 8;</code>
     */
    public Builder setAvatarUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setAvatarUrl(value);
      return this;
    }
    /**
     * <code>optional string avatar_url = 8;</code>
     */
    public Builder clearAvatarUrl() {
      copyOnWrite();
      instance.clearAvatarUrl();
      return this;
    }
    /**
     * <code>optional string avatar_url = 8;</code>
     */
    public Builder setAvatarUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAvatarUrlBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:soseedy.Teacher)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.instructure.soseedy.Teacher();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.instructure.soseedy.Teacher other = (com.instructure.soseedy.Teacher) arg1;
        id_ = visitor.visitInt(id_ != 0, id_,
            other.id_ != 0, other.id_);
        username_ = visitor.visitString(!username_.isEmpty(), username_,
            !other.username_.isEmpty(), other.username_);
        password_ = visitor.visitString(!password_.isEmpty(), password_,
            !other.password_.isEmpty(), other.password_);
        domain_ = visitor.visitString(!domain_.isEmpty(), domain_,
            !other.domain_.isEmpty(), other.domain_);
        token_ = visitor.visitString(!token_.isEmpty(), token_,
            !other.token_.isEmpty(), other.token_);
        name_ = visitor.visitString(!name_.isEmpty(), name_,
            !other.name_.isEmpty(), other.name_);
        shortName_ = visitor.visitString(!shortName_.isEmpty(), shortName_,
            !other.shortName_.isEmpty(), other.shortName_);
        avatarUrl_ = visitor.visitString(!avatarUrl_.isEmpty(), avatarUrl_,
            !other.avatarUrl_.isEmpty(), other.avatarUrl_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                id_ = input.readInt32();
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                username_ = s;
                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();

                password_ = s;
                break;
              }
              case 34: {
                String s = input.readStringRequireUtf8();

                domain_ = s;
                break;
              }
              case 42: {
                String s = input.readStringRequireUtf8();

                token_ = s;
                break;
              }
              case 50: {
                String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 58: {
                String s = input.readStringRequireUtf8();

                shortName_ = s;
                break;
              }
              case 66: {
                String s = input.readStringRequireUtf8();

                avatarUrl_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.instructure.soseedy.Teacher.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:soseedy.Teacher)
  private static final com.instructure.soseedy.Teacher DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Teacher();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.instructure.soseedy.Teacher getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Teacher> PARSER;

  public static com.google.protobuf.Parser<Teacher> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

