// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: soseedy.proto

package com.instructure.soseedy;

public interface TeacherOrBuilder extends
    // @@protoc_insertion_point(interface_extends:soseedy.Teacher)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string username = 2;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional string password = 3;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>optional string password = 3;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>optional string domain = 4;</code>
   */
  java.lang.String getDomain();
  /**
   * <code>optional string domain = 4;</code>
   */
  com.google.protobuf.ByteString
      getDomainBytes();

  /**
   * <code>optional string token = 5;</code>
   */
  java.lang.String getToken();
  /**
   * <code>optional string token = 5;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>optional string name = 6;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 6;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string short_name = 7;</code>
   */
  java.lang.String getShortName();
  /**
   * <code>optional string short_name = 7;</code>
   */
  com.google.protobuf.ByteString
      getShortNameBytes();

  /**
   * <code>optional string avatar_url = 8;</code>
   */
  java.lang.String getAvatarUrl();
  /**
   * <code>optional string avatar_url = 8;</code>
   */
  com.google.protobuf.ByteString
      getAvatarUrlBytes();
}
