# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import soseedy_pb2 as soseedy__pb2


class SoSeedyStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateTeacher = channel.unary_unary(
        '/soseedy.SoSeedy/CreateTeacher',
        request_serializer=soseedy__pb2.CreateTeacherRequest.SerializeToString,
        response_deserializer=soseedy__pb2.Teacher.FromString,
        )


class SoSeedyServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateTeacher(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SoSeedyServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateTeacher': grpc.unary_unary_rpc_method_handler(
          servicer.CreateTeacher,
          request_deserializer=soseedy__pb2.CreateTeacherRequest.FromString,
          response_serializer=soseedy__pb2.Teacher.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'soseedy.SoSeedy', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
