# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: soseedy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='soseedy.proto',
  package='soseedy',
  syntax='proto3',
  serialized_pb=_b('\n\rsoseedy.proto\x12\x07soseedy\"\x16\n\x14\x43reateTeacherRequest\"\x8e\x01\n\x07Teacher\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0e\n\x06\x64omain\x18\x04 \x01(\t\x12\r\n\x05token\x18\x05 \x01(\t\x12\x0c\n\x04name\x18\x06 \x01(\t\x12\x12\n\nshort_name\x18\x07 \x01(\t\x12\x12\n\navatar_url\x18\x08 \x01(\t2M\n\x07SoSeedy\x12\x42\n\rCreateTeacher\x12\x1d.soseedy.CreateTeacherRequest\x1a\x10.soseedy.Teacher\"\x00\x42)\n\x17\x63om.instructure.soseedyB\x0cSoSeedyProtoP\x01\x62\x06proto3')
)




_CREATETEACHERREQUEST = _descriptor.Descriptor(
  name='CreateTeacherRequest',
  full_name='soseedy.CreateTeacherRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=48,
)


_TEACHER = _descriptor.Descriptor(
  name='Teacher',
  full_name='soseedy.Teacher',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='soseedy.Teacher.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='username', full_name='soseedy.Teacher.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='soseedy.Teacher.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='domain', full_name='soseedy.Teacher.domain', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='soseedy.Teacher.token', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='soseedy.Teacher.name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='short_name', full_name='soseedy.Teacher.short_name', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avatar_url', full_name='soseedy.Teacher.avatar_url', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=193,
)

DESCRIPTOR.message_types_by_name['CreateTeacherRequest'] = _CREATETEACHERREQUEST
DESCRIPTOR.message_types_by_name['Teacher'] = _TEACHER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateTeacherRequest = _reflection.GeneratedProtocolMessageType('CreateTeacherRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATETEACHERREQUEST,
  __module__ = 'soseedy_pb2'
  # @@protoc_insertion_point(class_scope:soseedy.CreateTeacherRequest)
  ))
_sym_db.RegisterMessage(CreateTeacherRequest)

Teacher = _reflection.GeneratedProtocolMessageType('Teacher', (_message.Message,), dict(
  DESCRIPTOR = _TEACHER,
  __module__ = 'soseedy_pb2'
  # @@protoc_insertion_point(class_scope:soseedy.Teacher)
  ))
_sym_db.RegisterMessage(Teacher)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\027com.instructure.soseedyB\014SoSeedyProtoP\001'))

_SOSEEDY = _descriptor.ServiceDescriptor(
  name='SoSeedy',
  full_name='soseedy.SoSeedy',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=195,
  serialized_end=272,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateTeacher',
    full_name='soseedy.SoSeedy.CreateTeacher',
    index=0,
    containing_service=None,
    input_type=_CREATETEACHERREQUEST,
    output_type=_TEACHER,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SOSEEDY)

DESCRIPTOR.services_by_name['SoSeedy'] = _SOSEEDY

# @@protoc_insertion_point(module_scope)
